import {
  symbolCircle,
  symbolCross,
  symbolDiamond,
  symbolSquare,
  symbolStar,
  symbolTriangle,
  symbolWye,
  stackOrderAscending,
  stackOrderDescending,
  stackOrderInsideOut,
  stackOrderNone,
  stackOrderReverse,
  stackOffsetDiverging,
  stackOffsetExpand,
  stackOffsetNone,
  stackOffsetSilhouette,
  stackOffsetWiggle
} from "d3-shape";
export const PREFIX = "vix";
export const SCALES = [
  "auto",
  "linear",
  "pow",
  "sqrt",
  "log",
  "identity",
  "time",
  "band",
  "point",
  "ordinal",
  "quantile",
  "quantize",
  "utcTime",
  "sequential",
  "threshold"
];
export const SYMBOLS_MAP = {
  circle: symbolCircle,
  cross: symbolCross,
  diamond: symbolDiamond,
  square: symbolSquare,
  star: symbolStar,
  triangle: symbolTriangle,
  wye: symbolWye
};
export const STACK_ORDER_MAP = {
  ascnding: stackOrderAscending,
  descending: stackOrderDescending,
  insideout: stackOrderInsideOut,
  none: stackOrderNone,
  reverse: stackOrderReverse
};
export const STACK_OFFSET_MAP = {
  deverging: stackOffsetDiverging,
  expand: stackOffsetExpand,
  node: stackOffsetNone,
  silhouette: stackOffsetSilhouette,
  wiggle: stackOffsetWiggle
};
export const ORIENTATION = ["top", "right", "left", "bottom"];
export const SVG_EVENTS = [
  "onClick",
  "onContextMenu",
  "onDoubleClick",
  "onDrag",
  "onDragEnd",
  "onDragEnter",
  "onDragExit",
  "onDragLeave",
  "onDragOver",
  "onDragStart",
  "onDrop",
  "onMouseDown",
  "onMouseEnter",
  "onMouseLeave",
  "onMouseMove",
  "onMouseOut",
  "onMouseOver",
  "onMouseUp"
];

export const SVG_PRESENTATION_ATTRS = [
  "alignmentBaseline",
  "baselineShift",
  "clip",
  "clipPath",
  "clipRule",
  "color",
  "colorInterpolation",
  "colorInterpolationFilters",
  "colorProfile",
  "colorRendering",
  "cursor",
  "direction",
  "display",
  "dominantBaseline",
  "enableBackground",
  "fill",
  "fillOpacity",
  "fillRule",
  "filter",
  "floodColor",
  "floodOpacity",
  "fontFamily",
  "fontSize",
  "fontSizeAdjust",
  "fontStretch",
  "fontStyle",
  "fontVariant",
  "fontWeight",
  "glyphOrientationHorizontal",
  "glyphOrientationVertical",
  "imageRendering",
  "kerning",
  "letterSpacing",
  "lightingColor",
  "markerEnd",
  "markerMid",
  "markerStart",
  "mask",
  "opacity",
  "overflow",
  "pointerEvents",
  "shapeRendering",
  "stopColor",
  "stopOpacity",
  "stroke",
  "strokeDasharray",
  "strokeDashoffset",
  "strokeLinecap",
  "strokeLinejoin",
  "strokeMiterlimit",
  "strokeOpacity",
  "strokeWidth",
  "textAnchor",
  "textDecoration",
  "textRendering",
  "unicodeBidi",
  "visibility",
  "wordSpacing",
  "writingMode"
];
export const SVG_STYLE_ATTRS = ["className", "style"];
